name: AfGLock
version: 1.5.3
author: halberfan | AfGMedia
main: de.afgmedia.afglock2.main.AfGLock
api-version: 1.14
load: POSTWORLD

commands:
    lock:
        description: Der wichtigste Befehl fürs Lock-Plugin

